### ISSUE TITLE
Help in configuring HomeAssistant

### ISSUE THREAD

**Issue by riochicken** [gijsje/nextion-esphome#1]
Hi,

Thank you for your hard work! It looks amazing, I do have a question, since the link you mentioned creates a lot of mess on my HA installation, how did you do it? I of course managed to upload the tft file, that's the easy part, but how do you add the extra pages in HA? I tried uploading a seperate yaml file as you mentioned in the files somewhere and include it in my configuration.yaml but the computer says nooooo... ;) and where should I upload the pictures folder? To the HA I presume, but to which folder? Do I need to follow the original instructions to download the setup to my HA?

Thank you i advance for your answer!

Kind regards

RIchard

**Comment by gijsje** [comment]
You need to use the code in esphome.
The pics are used with the nextion edditor

**Comment by riochicken** [comment]
> You need to use the code in esphome.
> The pics are used with the nextion edditor

Typical case of duh... Thanks!
